language: node_js
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y default-jre
node_js:
- 5.0.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: npm run ci
env:
- ENV_TAG=qa
before_deploy:
- export ELASTIC_BEANSTALK_LABEL=$(echo $TRAVIS_BRANCH | grep "^[0-9].[0-9].[0-9]-\?[a-zA-Z]*\.\?[0-9]*$")
- export ENV_TAG=$(echo $ELASTIC_BEANSTALK_LABEL | cut -d - -f 2 | cut -d . -f 1 | grep "qa")
- export ELASTIC_BEANSTALK_ENV="quiet-goblin-"$ENV_TAG
deploy:
- provider: elasticbeanstalk
  region: us-west-2
  app: quiet-goblin
  bucket_name: elasticbeanstalk-us-west-2-615413463961
  skip_cleanup: true
  on:
    all_branches: true
    condition: ${#ENV_TAG} -gt 0
