language: node_js
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y default-jre
node_js:
- 5.0.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: npm run ci
env:
- DO_DEPLOY=
before_deploy:
- . ./deploy_vars.sh
- DO_DEPLOY=$(if [ $ENV_TAG ]; then echo true; fi)
- echo $DO_DEPLOY
- echo $ENG_TAG
deploy:
- provider: elasticbeanstalk
  region: us-west-2
  app: quiet-goblin
  bucket_name: elasticbeanstalk-us-west-2-615413463961
  skip_cleanup: true
  on:
    all_branches: true
    condition: true
