language: node_js
sudo: false
node_js:
- 5.0.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
script:
- npm run ci
- . ./deploy_vars.sh
deploy:
- provider: elasticbeanstalk
  region: us-west-2
  app: quiet-goblin
  bucket_name: elasticbeanstalk-us-west-2-615413463961
  skip_cleanup: true
  on:
    all_branches: true
    condition: $ENV_TAG
